name: Deploy prod

on:
  workflow_run:
    workflows: ["Deploy dev"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: >-
      ${{
        github.event.workflow_run.event == 'push' &&
        github.event.workflow_run.conclusion == 'success'
      }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-environment.yml
    with:
      ref: ${{ github.event.workflow_run.head_sha }}
      environment_name: prod
      cluster: prod-gcp
      manifest_path: .nais/nais-prod.yaml
      decorator_environment: prod
    secrets: inherit
