name: Deploy dev

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: nav-dekoratoren-testapp-dev
  cancel-in-progress: true

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
      - uses: pnpm/action-setup@v4
        with:
          version: 10.33.0
      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: pnpm build
      - name: Build and push image and SBOM to OCI registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: navno

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/setup@v1
        with:
          team: navno
      - name: Deploy to Nais
        run: |
          nais apply .nais/config.yaml \
            --environment dev-gcp \
            --set spec.image="${{ needs.build.outputs.image }}" \
            --wait
