name: Bekreft CSR med moduler
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy dev"]
    types: [completed]
jobs:
  bekreft:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: verify.yml
    with:
      path: /csr-med-moduler
      spec: tests/csr-med-moduler.spec.ts
    secrets: inherit
